server:
 port: 9010

spring:
 datasource: 
   url : jdbc:postgresql://revature1.cbarqkkjswqt.us-east-2.rds.amazonaws.com:5432/springdb
   username: springuser
   password: Passw0rd
   driver-class-name: org.postgresql.Driver
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
   ddl-auto: update
