# yaml stands for (YAML aint Markup Language)it uses whitespace and nesting for its properties
server:
  port: 9015
#if this was .properties spring.datasource.url = your url
# spring.datasource.username = username ... etc
spring:
  datasource:
    url: jdbc:postgresql://revature1.cbarqkkjswqt.us-east-2.rds.amazonaws.com:5432/springdb
    username: springuser
    password: Passw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
